### PR TITLE
Added browser dev tools and CORS learning resources

### PR DESCRIPTION
**Pull request by cheralathann**
CORS and Dev Tools links were added :)

### CODE REVIEW

**Review by shrutikapoor08 — CHANGES_REQUESTED** [review]
Can I request you to change the links to inline `[Link1]` `[Link2]` and so on (see HTML section) ?
Trying to keep the links to a minimum to avoid overwhelming people.

**Comment by cheralathann** [comment]
I also thought that beginners might be confused to start if we have too many resources. Can we categorize each section from beginner to advanced? Also, we can keep the section like a learning path, Whenever each section is being finished, they should be able to build something on their own. (We can keep some exercise or mini-projects as a milestone). Just my suggestion :)

**Review by shrutikapoor08 — APPROVED** [review]
This is awesome! thanks a lot for adding the React section specifically

**Comment by shrutikapoor08** [comment]
> I also thought that beginners might be confused to start if we have too many resources. Can we categorize each section from beginner to advanced? Also, we can keep the section like a learning path, Whenever each section is being finished, they should be able to build something on their own. (We can keep some exercise or mini-projects as a milestone). Just my suggestion :)

This is a great suggestion. I have written an article that references this checklist, and I have a learning path in it.

**Comment by cheralathann** [comment]
> This is a great suggestion. I have written an article that references this checklist, and I have a learning path in it.

Does the article has been published? If yes please share the link

**Pull request merged**
